FROM alpine

RUN apk add --update redis

CMD ["redis-server"]

# Run > docker build .
# Run docker run <imageid>

# Tagging the image for convinience
# docker build -t paihari/redis:latest
# docker run paihari/redis

