version: '3'
services:
  redis-server:
    image: 'redis'

  node-app:
    restart: always
    build: .
    ports:
      - "4001:8081"



#Run the docker compose
#docker-compose up


#Run the docker compose in background
# docker-compose up -d

#Stop the container started using docker compose
# docker-compose down

#To rebuild the images
#docker-compose up --build

#Automatic container restarts
#insert restart attribute
